# #
#   @usage              https://github.com/Aetherinox/csf-firewall
#   @type               github workflow
#
#   generates a list of ipsets which can then be used within host files, config server firewall, and various other apps
#
#   📄 bl-master.sh               generate master ipset | URLs: VARARG
#   📄 bl-plain.sh                generate ipset from online plain-text url / page | URLs: VARARG
#   📄 bl-json.sh                 generate ipset from json formatted web url. requires url and jq query | URLs: SINGLE
#   📄 bl-htmlip.sh               generate ipset by fetching HTML in web url, pulls only ips with grep rule (cant be changed) | URLs: SINGLE
#   📄 bl-html.sh                 generate ipset by fetching HTML in web url, does not run its own grep, must be specified in command | URLs: VARARG
#   📄 bl-block.sh                generate ipset by fetching locally specified file in /blocks/ repo folder
#   📄 bl-format.sh               generate ipset by from an existing list of IPs. does not generate ips itself. only validates a list provided
#   📄 bl-spf.sh                  generate ipset by fetching _spf ips from domain
#
#   local test requires the same structure as the github workflow
#       📁 .github
#           📁 blocks
#               📁 bruteforce
#                   📄 01.ipset
#               📁 privacy
#                   📄 01.ipset
#           📁 scripts
#               📄 bl-master.sh
#               📄 bl-plain.sh
#               📄 bl-json.sh
#               📄 bl-htmlip.sh
#               📄 bl-html.sh
#               📄 bl-block.sh
#               📄 bl-format.sh
#               📄 bl-spf.sh
#           📁 workflows
#               📄 blocklist-generate.yml
# #

name: "🧱 Blocklist › Generate"
run-name: "🧱 Blocklist › Generate"

# #
#   triggers
# #

on:

    # #
    #   Trigger > Workflow Dispatch
    # #

    workflow_dispatch:
      inputs:

        # #
        #   true:     runs all actions, even ones not scheduled
        #   false:    only scheduled tasks will run
        # #
  
        RUN_ALL_ACTIONS:
          description:  "📑 Run All Actions"
          required:     true
          default:      false
          type:         boolean

    # #
    #   Trigger > Cron Schedule
    # #

    schedule:
    # - cron: '0 2,8,14,20 * * *'
      - cron: '0 */12 * * *'
      - cron: '0 0 * * *'

# #
#   environment variables
# #

env:
    BOT_NAME_1:           EuropaServ
    BOT_NAME_DEPENDABOT:  dependabot[bot]

# #
#   jobs
# #

jobs:

    # #
    #   Job > Setup
    # #

    blocklist-setup:
        name: >-
          📦 Setup
        runs-on: ubuntu-latest
        # runs-on: apollo-x64
        timeout-minutes: 60
        steps:

            - name: "✅ Start"
              id: task_setup_start
              run: |
                echo "Starting blocklist build script"

            # #
            #   Job > Checkout
            # #

            - name: "☑️ Checkout"
              id: task_setup_checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            # #
            #   Generate > Install Packages
            # #

            - name: "🧱 Install Packages"
              id: task_setup_install
              run: |
                  sudo apt-get install -y ipcalc ed html2text whois uuid-runtime autoconf

            # #
            #   Generate > Cache Packages
            # #

            - name: "🧱 Cache Packages"
              uses: awalsh128/cache-apt-pkgs-action@latest
              with:
                  packages: ipcalc ed html2text whois uuid-runtime
                  version: 1.0

    # #
    #   Job > Blocklist > Master
    # #

    blocklist-generate:
        name: >-
          📋 Generate › Blocklist
        runs-on: ubuntu-latest
        # runs-on: apollo-x64
        timeout-minutes: 60
        needs: [ blocklist-setup ]
        steps:

            # #
            #   Generate > Checkout
            # #

            - name: "☑️ Checkout"
              id: task_blocklist_generate_checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: "🧱 Install Packages"
              id: task_blocklist_generate_install
              run: |
                  sudo apt-get install -y ipcalc ed html2text whois uuid-runtime autoconf

            # #
            #   Generate > Configure
            #
            #   this step installs packages we need to manage ipsets.
            #       - iprange
            #         this package allows us to convert ip ranges into a CIDR formatted ip
            #         10.10.0.1-10.10.0.9  =>   10.10.0.1
            #                                   10.10.0.2/31
            #                                   10.10.0.4/30
            #                                   10.10.0.8/31
            #       https://github.com/firehol/iprange
            # #

            - name: "⚙️ Configure"
              id: task_blocklist_generate_configure
              run: |
                  git clone https://github.com/firehol/iprange.git ./.temp/iprange
                  cd .temp/iprange
                  ./autogen.sh
                  ./configure --disable-man
                  sudo make && make install

            # #
            #   Generate > Set Template Permissions
            # #

            - name: "☑️ Set Permissions"
              id: task_blocklist_generate_perms
              run: |

                  #   Set Permissions
                  chmod +x ".github/scripts/bl-master.sh"
                  chmod +x ".github/scripts/bl-format.sh"
                  chmod +x ".github/scripts/bl-htmlip.sh"
                  chmod +x ".github/scripts/bl-html.sh"
                  chmod +x ".github/scripts/bl-block.sh"
                  chmod +x ".github/scripts/bl-json.sh"
                  chmod +x ".github/scripts/bl-plain.sh"
                  chmod +x ".github/scripts/bl-spf.sh"
                  chmod +x ".github/scripts/bl-whois.sh"
                  chmod +x ".github/scripts/bt-transmission.sh"
                  chmod +x ".github/scripts/update-readme.sh"
                  chmod +x ".github/scripts/tool-range-iprange.sh"

            # #
            #   Generate > Set Env Variables
            # #

            - name: "📦 Set Env Variables"
              id: task_commit_pre
              run: |
                  useragent="${{ vars.API_USERAGENT }}"
                  echo "USERAGENT=$(echo $useragent)" >> $GITHUB_ENV

            # #
            #   Generate > Master
            # #

            - name: "🧱 Generate › Master"
              id: task_blocklist_generate_master
              run: |
                  run_master=".github/scripts/bl-master.sh blocklists/master.ipset ${{ secrets.API_01_FILE_01 }} ${{ secrets.API_01_FILE_02 }} ${{ secrets.API_01_FILE_03 }} ${{ secrets.API_01_FILE_04 }} ${{ secrets.API_01_FILE_05 }} ${{ secrets.API_01_FILE_06 }} ${{ secrets.API_01_FILE_07 }} ${{ secrets.API_01_FILE_08 }} ${{ secrets.API_01_FILE_09 }}"
                  eval "./$run_master"

                  run_highrisk=".github/scripts/bl-htmlip.sh blocklists/highrisk.ipset ${{ secrets.API_01_HIGHRISK_URL }} '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}'"
                  eval "./$run_highrisk"

    # #
    #   Job > Commit
    # #

    blocklist-commit:
        name: >-
          📋 Commit
        runs-on: ubuntu-latest
        # runs-on: apollo-x64
        timeout-minutes: 60
        needs: [ blocklist-setup, blocklist-generate ]
        steps:

            # #
            #   Generate > Checkout
            # #

            - name: "☑️ Commit › Checkout"
              id: task_blocklist_master_checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            # #
            #   Generate  > Artifact > Download
            # #

            - name: "🎁 Commit › Download Artifact"
              id: task_commit_artifact_download
              uses: actions/download-artifact@v4
              with:
                  name: blocklist-latest
                  path: ./

            # #
            #   Commit > Precommit
            # #

            - name: "📦 Commit › Pre-commit"
              id: task_commit_pre
              run: |
                  now=$(date -u '+%m/%d/%Y %H:%M')
                  commit_label="Sync" >> $GITHUB_ENV
                  commit_message="\`️️🔒 $commit_label 🔒\` \`$now UTC\`" >> $GITHUB_ENV
                  echo "COMMIT_MESSAGE=$(echo $commit_message)" >> $GITHUB_ENV
                  echo "NOW=$(echo $now)" >> $GITHUB_ENV

            # #
            #   Update README
            # #

            - name: "📄 Update README"
              id: task_commit_readme_update
              run: |
                  chmod +x ".github/scripts/update-readme.sh"
                  run_readme=".github/scripts/update-readme.sh README.md"
                  eval "./$run_readme"

            # #
            #   GPG Key
            # #

            - name: "📦 Commit › GPG Key"
              id: task_commit_gpg
              uses: crazy-max/ghaction-import-gpg@v6
              with:
                  gpg_private_key: ${{ secrets.ADMINSERV_GPG_KEY_ASC }}
                  passphrase: ${{ secrets.ADMINSERV_GPG_PASSPHRASE }}
                  git_user_signingkey: true
                  git_commit_gpgsign: true

            # #
            #   Commit > Commit
            # #

            - name: "📦 Commit › Execute"
              id: task_commit_execute
              uses: stefanzweifel/git-auto-commit-action@v5
              with:
                  commit_message: ${{ env.COMMIT_MESSAGE }}
                  commit_author: "${{ steps.task_commit_gpg.outputs.name }} <${{ steps.task_commit_gpg.outputs.email }}>"
                  commit_user_name: ${{ steps.task_commit_gpg.outputs.name }}
                  commit_user_email: ${{ steps.task_commit_gpg.outputs.email }}
